### ISSUE TITLE
Should this be deprecated now that the Trello extension has been released?

### ISSUE THREAD

**Issue by tnorthcutt** [trello-archive/chromello#2]
http://blog.trello.com/trello-chrome-extension/

**Comment by StephenFluin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IEaDeIn0&#x2F;41-march-project"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> March Project</a>
