### ISSUE TITLE
Support for notifications and badges

### ISSUE THREAD

**Issue by jdrew1303** [trello-archive/chromello#3]
Hi @PeEllAvaj 

This is a two part issue: 
- I was wondering if this is a mirror of the official plugin?
- If so I've added support for native notifications and badges to this. Would you be interested in me opening a pull request for this functionality?

**Comment by PeEllAvaj** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IEaDeIn0&#x2F;41-march-project"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> March Project</a>

**Comment by jdrew1303** [comment]
@PeEllAvaj I dont have access to the card or board.

**Comment by StephenFluin** [comment]
@jdrew1303 I'm not sure how that comment got added, it wasn't relevant to your questions.

This is a precursor to the official browser extension. We're working on open sourcing the new version, but it might be a little while while it undergoes cleanup.

**Comment by jdrew1303** [comment]
@PeEllAvaj No problem :smile: If you're using the git powerup I think it might link to issues. 

Great, cant wait to see it. :)
